var SEPARATOR = ',';

// Separate three things (kanji, reading and meaning) with the separator given above
var WORDS = 
[
    "ギャップ萌え,ぎゃっぷもえ,when a character does something completely contradictory to what their usual habits",
    "雪だるま,ゆきだるま,snowman",
    "イケボ,いけぼ,attractive male voice; sexy male voice",
    "イケメン,いけめん,good-looking guy; handsome man; hunk; Adonis; cool guy​",
    "絶対領域,ぜったいりょういき,the area of bare skin in the gap between overknee socks and a miniskirt",
    "怪獣,かいじゅう,monster",
    "百万長者,ひゃくまんちょおじゃ,millionaire",
    "肉付く,にくづ,to put on flesh; to get fat; to gain weight",
    "巨乳,きょにゅう,huge breasts",
    "最近,さいきん,recently; lately; these days; nowadays; right now",
    "爆乳,ばくにゅう,enormous breasts",
    "わくわく,,trembling; getting nervous; excited; thrilled",
    "金持ち,かねもち,rich person",
    "美人,びじん,beautiful woman",
    "どこの方ですか,どこのかたですか,Where are you from?",
    "もっと練習が必要です,もっとれんしゅうがひつよう,Need more practice",
    "クソワロタ,くそわろた,roll on the floor laughing; ROFL",
    "なんてこった,,what the hell; oh, great!; son of a gun; holy mackerel; oh no!; holy cow!; damn!",
    "ばぶみ,,cuteness; feelings of motherhood",
    "さっきの歌,,Previous song",
    "前の歌,,Previous song",
    "先の歌,,Previous song",
    "おねんね,,Bed time for a baby",
    "僕のバレンタインになりませんか,ぼくのばれんたいんになりませんか,Would you like to be my valentine?",
    "また今度ね,またこんどね,See you next time",
    "しょうがない,,It can't be helped",
    "ダスイ,,Lame",
    "きもい,,Gross",
    "すごく,,Very (strong word)",
    "むかつく,,Annoying; irritating",
    "ぶりっこ,,woman or girl who acts cute by playing innocent and helpless",
    "猫を被る,ねこをかぶる,to feign friendliness; to play the hypocrite​",
    "もぐもぐ,,chewing (food)",
    "マニアック,,maniac (as in rabid sport fan); enthusiast",
    "みだらな,,obscene; indecent; lewd; bawdy; loose; improper; dirty",
    "あざーす,,thanks​",
    "どスケベ,,sex fiend; lecher; pervert​",
    "自動販売機,じどうはんばいき,Vending machine",
    "スマホ,すまほ,Smartphone",
    "粉食,ふんしょく,powdered food",
    "縦書き,たてがき,Vertical writing",
    " 横書き,よこがき,Horizontal writing",
    "太もも,ふともも,Thighs",
    "良さげ,よさげ,Seemingly good",
    "目標,もくひょう,Target; goal",
    "大人っぽい,おとなっぽい,adult-like",
    "いじめっ子,いじめっこ,Bully",
    "お前 なんか ゆうてたやろ？！,,Are you talking smack about me?",
    "手伝ってくれてありがとう,てつだってくれてありがとう,Thank you for your help",
    "あざまる水産,あざまるすいさん,a way to say thank you (used by high school girls)",
    "一期一会,いちごいちえ,once-in-a-lifetime encounter (hence should be cherished as such)",
    "七転び八起き,ななころびやおき,not giving up; keeping at it until one succeeds; falling seven times; getting up eight times",
    "リア充,りあじゅう,person who is satisfied with their real life; normie",
    "継続は力なり,けいぞくはちからなり,whatever doesn't kill us only makes us stronger; slow but steady wins the race",
    "駄洒落,だじゃれ,feeble joke; bad pun",
    "もうかりまっか？,,kansai-ben how are you?",
    "脱線,だっせん,derailment",
    "恋人,こいびと,lover; sweetheart; boyfriend; girlfriend",
    "アプリ,あぷり,app; application",
    "色っぽい,いろっぽい,amorous; sexy; voluptuous; erotic",
    "もしかして形から入るタイプですか？,,Could it be that you’re someone who puts appearances before substance?",
    "しらんけど,,",
    "さすがだね,,",
    "ごろごろ,,",
    "かくれんぼ,,hide-n-seek",
    "おっちょこちょい ,,careless person; scatterbrain; birdbrain",
    "大根足,だいこんあし,thick legs; fat legs; cankle; cankles",
    "知らんけど,,",
    "なんくるないさ,,",
    "知らんけど,,I don't know; dunno",
    "蝸牛,かたつむり,snail",
    "大草原,だいそうげん,laughter; LOL​",
    "助平,すけべ,lewdness; lewd person; lecher",
    "下ネタ,しもねた,indecent topic; bawdy subject; sex talk",
    "なんくるない(さ～),,don't worry; be happy;Ryuukyuu dialect",
    "近親相姦,きんしんそうかん,incest",
    "生理,せいり,menstruation; one's period; menses​",
    "男らしい,おとこらしい,manly; masculine; like a man",
    "動画 ,どうが,video; movie; moving picture",
    "子供らしい,こどもらしい,childish; child-like; innocent; naive",
    "将来の夢,しょうらいのゆめ,dream for the future; hopes for the future",
    "ネタバレ,ねたばれ,spoiler; spoiling a story",
    "月がきれいですね,つきがきれいですね,I love you (indirect way from a book)",
    "君はもっときれい,きみはもっときれい,You are prettier (response 1)",
    "届かないから綺麗なんです,,It's beautiful because I can't reach it (response 2)",
    "知ったかぶりで話す,,",
    "口寂しい,くちさびしい,longing to have or put something in one's mouth",
    "えっど,,",
    "変換ミス,へんかんみす,typographical error caused by selecting wrong kanji",
    "畑水練,はたけすいれん,useless book learning",
    "臥薪嘗胆,がしんしょうたん,going through thick and thin to attain one's objective; enduring unspeakable hardships for the sake of vengeance",
    "博引旁証,はくいんぼうしょう,citing copious references​",
    "チョメチョメ,ちょめちょめ,blankety-blank; bleep; yada yada; xxx",
    "ガキども,ががきども,damn kids",
    "嗚呼嗚呼,ああああ,aaah!; oooh!; oh no!; oh boy!​",
    "パソ婚,ぱそこん,marriage between two people who met over the Internet",
    "辻斬り,つじぎり,killing a passerby in order to test a new sword",
    "潮吹き,しおふき,spouting (e.g. of a whale, blowhole, etc.); blowing water​"
];